const PRODUCT_LOADING = "PRODUCT_LOADING";
const PRODUCT_ERROR = "PRODUCT_ERROR";
const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";

const CURRENT_PRODUCT_LOADING = "CURRENT_PRODUCT_LOADING";
const CURRENT_PRODUCT_ERROR = "CURRENT_PRODUCT_ERROR";
const CURRENT_PRODUCT_SUCCESS = "CURRENT_PRODUCT_SUCCESS";
const FILTER_FOR_MEN = "FILTER_FOR_MEN";
const FILTER_FOR_WOMEN = "FILTER_FOR_WOMEN";

export {
  PRODUCT_ERROR,
  PRODUCT_LOADING,
  PRODUCT_SUCCESS,
  CURRENT_PRODUCT_ERROR,
  CURRENT_PRODUCT_LOADING,
  CURRENT_PRODUCT_SUCCESS,
  FILTER_FOR_MEN,
  FILTER_FOR_WOMEN,
};
